name: Build EXE Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install pyinstaller yt-dlp
    - name: Build EXE
      run: pyinstaller --onefile downloader.py
    - name: Upload EXE Result
      uses: actions/upload-artifact@v3
      with:
        name: Downloader-Windows-EXE
        path: dist/downloader.exe
